# Generated by Django 2.2.1 on 2019-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default='Buy', max_length=55),
        ),
    ]
