# Generated by Django 2.2.1 on 2019-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default='Buy', max_length=55),
        ),
    ]
