# Generated by Django 2.1.8 on 2019-06-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190605_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(blank=True, choices=[('Louer', 'Louer'), ('Vendre', 'Vendre')], max_length=55),
        ),
    ]
