# Generated by Django 2.1.8 on 2019-06-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190605_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='style',
            field=models.CharField(blank=True, choices=[('Appartement', 'Appartement'), ('Etage de Villa', 'Etage de Villa'), ('Villa', 'Villa'), ('Villa Inachevée', 'Villa Inachevée'), ('Immeuble', 'Immeuble')], max_length=55),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, choices=[('Nabeul', 'Nabeul'), ('Sousse', 'Sousse')], max_length=55),
        ),
    ]
