# Generated by Django 2.1.8 on 2019-06-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190622_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='placeparking',
            field=models.BooleanField(default=False),
        ),
    ]
