# Generated by Django 2.1.8 on 2019-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190622_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='piscine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='terasse',
            field=models.BooleanField(default=False),
        ),
    ]
