# Generated by Django 2.1.8 on 2019-06-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactterrain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactterrain',
            new_name='Contact',
        ),
    ]
