# Generated by Django 2.1.8 on 2019-06-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='type',
            field=models.CharField(blank=True, choices=[('Commercial', 'Commercial'), ('Habitation', 'Habitation'), ('Agriculture', 'Agriculture'), ('Proposition immobilière', 'Proposition immobilière')], max_length=55),
        ),
    ]
