# Generated by Django 2.1.8 on 2019-06-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0002_terrain_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrain',
            old_name='lot_size',
            new_name='surface',
        ),
    ]
